# Importing relevant libraries

In [1]:
import pandas as pd
import numpy as np
import re

# Importing data

In [2]:
shark_attacks = pd.read_csv('C:/Users/pfaprado/Documents/IronHack/2021-01-22-project-shark-attack/attacks.csv', encoding='latin1')

# Preliminary analysis of data

In [3]:
# Let's show all the columns available through a max_columns = None and a head method.

pd.options.display.max_columns = None
shark_attacks.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

## Size of the dataframe

In [4]:
# Let's check the number of elements in our dataframe.

shark_attacks.size

# We have about 617352 elements.

617352

## Shape of the dataframe

In [5]:
# Let's check the shape of our dataframe.

shark_attacks.shape

# We have 24723 entries of 24 types of data.

(25723, 24)

## Null-count and data types of the dataframe

In [6]:
# Let's check the non-null count and type of our data.

shark_attacks.info()

# Too many data entries without many infos such as Age, Time, Sex, Fatal, etc. Last columns can't be used.
# Year is a float64, should have been an integer.
# Age should have been specified as integer.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8702 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(2), object(22)
memory usage: 4.7+ MB

In [7]:
# Specifically, about the types of data columns.

shark_attacks.dtypes

Case Number                object
Date                       object
Year                      float64
Type                       object
Country                    object
Area                       object
Location                   object
Activity                   object
Name                       object
Sex                        object
Age                        object
Injury                     object
Fatal (Y/N)                object
Time                       object
Species                    object
Investigator or Source     object
pdf                        object
href formula               object
href                       object
Case Number.1              object
Case Number.2              object
original order            float64
Unnamed: 22                object
Unnamed: 23                object
dtype: object

## Columns of the dataframe

In [8]:
# Let's check all the columns availables. There are a bunch of columns with strange names at the end.

shark_attacks.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [9]:
# Let's check how many nulls we have in our dataset in each column.

null_cols = shark_attacks.isnull().sum()

null_cols

Case Number               17021
Date                      19421
Year                      19423
Type                      19425
Country                   19471
Area                      19876
Location                  19961
Activity                  19965
Name                      19631
Sex                       19986
Age                       22252
Injury                    19449
Fatal (Y/N)               19960
Time                      22775
Species                   22259
Investigator or Source    19438
pdf                       19421
href formula              19422
href                      19421
Case Number.1             19421
Case Number.2             19421
original order            19414
Unnamed: 22               25722
Unnamed: 23               25721
dtype: int64

# Jaws Adventures: marketing shark feeding

In [10]:
"""
Our company, "Jaws Adventures", offers scuba diving for people.
We would like to analyse and market a new product: shark feeding.
However people may express distress to the idea of feeding sharks and the risks involved.
Let's analyse whether feeding sharks is safer than other activities already offered by our company.
"""

"""
For this, we will need to pull the data from columns:
- Activity (categorical)
- Fatal (Y/N) (categorical, binary: Y/N)

However, we know that the database is kind of messy, so we will need to do some data wrangling (cleaning) before.
"""

fatality_activity = shark_attacks[['Activity','Fatal (Y/N)']]

fatality_activity

          Activity Fatal (Y/N)
0         Paddling           N
1         Standing           N
2          Surfing           N
3          Surfing           N
4      Free diving           N
...            ...         ...
25718          NaN         NaN
25719          NaN         NaN
25720          NaN         NaN
25721          NaN         NaN
25722          NaN         NaN

[25723 rows x 2 columns]

In [11]:
# Let's count all the occurrences present in the column Fatal.

shark_attacks['Fatal (Y/N)'].value_counts()

# Highest portion of shark attacks are non-fatal.

N          4293
Y          1388
UNKNOWN      71
 N            7
2017          1
M             1
N             1
y             1
Name: Fatal (Y/N), dtype: int64

In [12]:
shark_attacks['Activity'].value_counts()

# Highest portion occurred during surfing, swimming or fishing (apparently).
# !However there are way too many categories to affirm anything at this point!

Surfing                                                                               971
Swimming                                                                              869
Fishing                                                                               431
Spearfishing                                                                          333
Bathing                                                                               162
                                                                                     ...
Board sailing                                                                           1
The 3540-ton Alfonso Penna was torpedoed & sunk by the Italian submarine Barbarigo      1
Finning the shark                                                                       1
Photo shoot                                                                             1
Swimming near pod of whales                                                             1
Name: Activity, Length: 1532, dtype: int64

In [13]:
# Let's understand the cases where the entries are null for Activity.

null_display_activity = shark_attacks[shark_attacks['Activity'].isnull() == True]
null_display_activity

# There is no apparent reason or correlation between null entries of Activity to other categories.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
47,2018.01.28,28-Jan-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Cone Bay,NaN,male,M,18,Injuries to right leg,N,08h00,Bull shark,"ABC.net.au, 01/28/2018",2018.01.28-ConeBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.01.28,2018.01.28,6256.0,NaN,NaN
108,2017.07.29.a,29-Jul-2017,2017.0,Unprovoked,USA,South Carolina,"DeBordieu Colony, Georgetown County",NaN,female x 2,F,12,Bite to left thigh / minor injury,N,Afternoon,NaN,"C. Creswell, GSAF",2017.07.29.a-Georgetown.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.29.a,2017.07.29.a,6195.0,NaN,NaN
112,2017.07.23.b,23-Jul-2017,2017.0,Unprovoked,USA,New Jersey,Ventnor,NaN,Isabella Smith,F,NaN,Minor injury to hand,N,NaN,Sandtiger shark 2',A. Smith,2017.07.23.b-Smith.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.23.b,2017.07.23.b,6191.0,NaN,NaN
114,2017.07.22,22-Jul-2017,2017.0,Unprovoked,USA,Florida,"Snipes Point, Monroe County",NaN,female,F,40,Foot bitten,N,12h30,"""A small shark""","NBC Miami, 7/23/2017",2017.07.22-Keys.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.22,2017.07.22,6189.0,NaN,NaN
154,2017.04.17.b,17-Apr-2017,2017.0,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",NaN,NaN,NaN,NaN,Minor bite to the foot,N,Afternoon,NaN,"Daytona Beach News-Journal, 4/17/2017",2017.04.17.b-Volusia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.04.17.b,2017.04.17.b,6149.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Let's understand the cases where the entries are null for Fatal.

null_display_fatal = shark_attacks[shark_attacks['Fatal (Y/N)'].isnull() == True]
null_display_fatal

# There is no apparent reason or correlation between null entries of Fatal to other categories.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0,NaN,NaN
76,2017.10.01,01-Oct-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,31,FATAL,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01,6227.0,NaN,NaN
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b,6224.0,NaN,NaN
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,25,"FATAL, but death was probably due to drowning",NaN,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b,6219.0,NaN,NaN
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Lacerations to left foot,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b,6205.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# Let's check for duplicates in our database and remove them:

before = len(shark_attacks)
shark_attacks = shark_attacks.drop_duplicates()
after = len(shark_attacks)
print('Number of duplicate records dropped: ', str(before - after))

Number of duplicate records dropped:  19411

In [16]:
# That's how our database is now:

shark_attacks.head(7)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris,M,NaN,"No injury, board bitten",N,NaN,NaN,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.b,2018.06.03.b,6298.0,NaN,NaN
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN

## Data Cleaning: 'Fatal (Y/N)'

In [17]:
# Let's check the unique values of the column Fatal (Y/N) and its incidence in our database.

print(f"""
These are the occurrences of the values for Fatal (Y/N):
{shark_attacks['Fatal (Y/N)'].value_counts()}
""")

print(f"""
These are the unique values of the Fatal (Y/N) column:
{set(shark_attacks['Fatal (Y/N)'])}

We will need to standardize it all in Y and N.
To do this, we will need to:

1. Check rows of data where anything else than Y/N appears (UNKNOWN, 2017, nan, M... about 73 occurrences).
    We may be able to attribute it to Y/N if Fatal/FATAL appears/fatal appears in other columns of the entry.
2. If not, drop the rows of these data values.
3. Transform the series from the dataframe into a list.
4. Upper case the strings.
5. Strip the strings of spaces after and before the character.
""")

These are the occurrences of the values for Fatal (Y/N):
N          4293
Y          1388
UNKNOWN      71
 N            7
N             1
2017          1
M             1
y             1
Name: Fatal (Y/N), dtype: int64


These are the unique values of the Fatal (Y/N) column:
{nan, 'UNKNOWN', ' N', 'N ', '2017', 'N', 'Y', 'M', 'y'}

We will need to standardize it all in Y and N.
To do this, we will need to:

1. Check rows of data where anything else than Y/N appears (UNKNOWN, 2017, nan, M... about 73 occurrences).
    We may be able to attribute it to Y/N if Fatal/FATAL appears/fatal appears in other columns of the entry.
2. If not, drop the rows of these data values.
3. Transform the series from the dataframe into a list.
4. Upper case the strings.
5. Strip the strings of spaces after and before the character.

### Checking uniques.

In [18]:
#Let's examine the case of 2017. There is only one entry classified as 2017.

case_2017_list = shark_attacks.loc[shark_attacks['Fatal (Y/N)'] == '2017']

case_2017_list

# As there is no information regarding the survivability on other columns,
# we will dismiss this entry in the dropping section.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
786,2012.06.10,10-Jun-2012,2012.0,Provoked,ITALY,Sardinia,Muravera,Attempting to rescue an injured & beached shark,Giorgio Zara,M,57,Lower left leg injured PROVOKED ACCIDENT,2017,Morning,"Blue shark, 2.5m","D. Puddo, 6/11/2012",2012.06.10-Zara.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.06.10,2012.06.10,5517.0,NaN,NaN

In [19]:
# Let's examine the case of UNKNOWN. There are many entries classified as UNKNOWN.

case_UNKNOWN = shark_attacks.loc[shark_attacks['Fatal (Y/N)'] == 'UNKNOWN']
print(case_UNKNOWN)

# Printaremos também os índices referentes à entrada UNKNOWN. Futuramente retiraremos as linhas com base nessa lista.

case_UNKNOWN_list = list(case_UNKNOWN.index)
print(case_UNKNOWN_list)

# Examining the set of unique values of injury, we don't have any other relevant info on the fatality of the entries.
# So we can't take any action to classify these entries neither as Y nor as N.

set(case_UNKNOWN['Injury'])

# We will dismiss these entries since there is no info about fatality in the adjacent columns.

       Case Number           Date    Year        Type    Country  \
624     2013.09.08    08-Sep-2013  2013.0  Unprovoked        USA
1270  2008.04.20.a    20-Apr-2008  2008.0  Unprovoked  AUSTRALIA
2250    1997.06.07    07-Jun-1997  1997.0  Unprovoked     BRAZIL
2260    1997.02.21    21-Feb-1997  1997.0  Unprovoked        USA
2267    1996.12.29    29-Dec-1996  1996.0  Unprovoked  AUSTRALIA
...            ...            ...     ...         ...        ...
6167  1617.00.00.R  Reported 1617  1617.0  Unprovoked      INDIA
6169    1595.00.00           1595  1595.0  Unprovoked      INDIA
6171    1555.00.00           1555  1555.0  Unprovoked        NaN
6172    1554.00.00       Ca. 1554  1554.0  Unprovoked     FRANCE
6277       ND.0025    Before 1927     0.0  Unprovoked  AUSTRALIA

                   Area                            Location  \
624      South Carolina  St. Helena Island, Beaufort County
1270    New South Wales                       Crescent Head
2250     Rio de Janeiro          Copacabana, Rio de Janeiro
2260             Hawaii                 Sunset Beach, O'ahu
2267         Queensland                        Coolum Beach
...                 ...                                 ...
6167        West Bengal                        Ganges Delta
6169             Kerala                        River Cochin
6171                NaN                                 NaN
6172  Nice & Marseilles                                 NaN
6277    New South Wales      Spectacle Island, Port Jackson

                                               Activity  \
624                                                 NaN
1270                                                NaN
2250                                            Bathing
2260                                                NaN
2267                                            Surfing
...                                                 ...
6167                                                NaN
6169  Ship lay at anchor & man was working on its ru...
6171                                           Swimming
6172                                                NaN
6277                                                NaN

                               Name Sex   Age  \
624                          female    F  NaN
1270                Jamie Adlington    M  NaN
2250              José Luiz Lipiani    M  NaN
2260                Gersome Perreno    M  NaN
2267                     Blair Hall    M   18
...                             ...  ...  ...
6167                  Indian people  NaN  NaN
6169                           male    M  NaN
6171                           male    M  NaN
6172          males (wearing armor)    M  NaN
6277  male, the Sergeant of Marines    M  NaN

                                                 Injury Fatal (Y/N)   Time  \
624                                          No details     UNKNOWN    NaN
1270                                                NaN     UNKNOWN    NaN
2250                                                NaN     UNKNOWN    NaN
2260                                         No details     UNKNOWN    NaN
2267                                                NaN     UNKNOWN  18h00
...                                                 ...         ...    ...
6167                                                NaN     UNKNOWN    NaN
6169  Leg severed mid-thigh, hand severed, arm above...     UNKNOWN    NaN
6171                                                NaN     UNKNOWN    NaN
6172                                                NaN     UNKNOWN    NaN
6277                                                NaN     UNKNOWN    NaN

                   Species                      Investigator or Source  \
624                     NaN                           WIS-TV, 9/9/2013
1270     Tiger shark, 2.3m                              T. Peake, GSAF
2250                    NaN                            Globo, 6/9/1997
2260                    NaN                                  G. Balazs
2267                    NaN            The Advertiser, 12/30/1996, p.3
...                     ...                                        ...
6167                    NaN    H. Edwards, p.31, citing Samuel Purchas
6169                    NaN  The Voyage of John Huyghen van Linschoten
6171                    NaN                               Olaus Magnus
6172  Possibly white sharks                               G. Rondelet
6277                    NaN                                  H. Capper

                                  pdf  \
624          2013.09.08-St-Helena.pdf
1270       2008.04.20.a-Adlington.pdf
2250        1997.06.07-NV-Lipiani.pdf
2260        1997.02.21-NV-Perreno.pdf
2267         1996.12.29-BlairHall.pdf
...                               ...
6167           1617.00.00-Purchas.pdf
6169            1595.00.00-Cochin.pdf
6171    1555.00.00 - Olaus Magnus.pdf
6172          1554.00.00-Rondelet.pdf
6277  ND-0025-Sgt-SpectacleIsland.pdf

                                           href formula  \
624   http://sharkattackfile.net/spreadsheets/pdf_di...
1270  http://sharkattackfile.net/spreadsheets/pdf_di...
2250  http://sharkattackfile.net/spreadsheets/pdf_di...
2260  http://sharkattackfile.net/spreadsheets/pdf_di...
2267  http://sharkattackfile.net/spreadsheets/pdf_di...
...                                                 ...
6167  http://sharkattackfile.net/spreadsheets/pdf_di...
6169  http://sharkattackfile.net/spreadsheets/pdf_di...
6171  http://sharkattackfile.net/spreadsheets/pdf_di...
6172  http://sharkattackfile.net/spreadsheets/pdf_di...
6277  http://sharkattackfile.net/spreadsheets/pdf_di...

                                                   href Case Number.1  \
624   http://sharkattackfile.net/spreadsheets/pdf_di...    2013.09.08
1270  http://sharkattackfile.net/spreadsheets/pdf_di...  2008.04.20.a
2250  http://sharkattackfile.net/spreadsheets/pdf_di...    1997.06.07
2260  http://sharkattackfile.net/spreadsheets/pdf_di...    1997.02.21
2267  http://sharkattackfile.net/spreadsheets/pdf_di...    1996.12.29
...                                                 ...           ...
6167  http://sharkattackfile.net/spreadsheets/pdf_di...  1617.00.00.R
6169  http://sharkattackfile.net/spreadsheets/pdf_di...    1595.00.00
6171  http://sharkattackfile.net/spreadsheets/pdf_di...    1555.00.00
6172  http://sharkattackfile.net/spreadsheets/pdf_di...    1554.00.00
6277  http://sharkattackfile.net/spreadsheets/pdf_di...       ND.0025

     Case Number.2  original order Unnamed: 22 Unnamed: 23
624     2013.09.08          5679.0         NaN         NaN
1270  2008.04.20.a          5033.0         NaN         NaN
2250    1997.06.07          4053.0         NaN         NaN
2260    1997.02.21          4043.0         NaN         NaN
2267    1996.12.29          4036.0         NaN         NaN
...            ...             ...         ...         ...
6167  1617.00.00.R           136.0         NaN         NaN
6169    1595.00.00           134.0         NaN         NaN
6171    1555.00.00           132.0         NaN         NaN
6172    1554.00.00           131.0         NaN         NaN
6277       ND.0025            26.0         NaN         NaN

[71 rows x 24 columns]
[624, 1270, 2250, 2260, 2267, 2295, 2307, 2323, 2328, 2388, 2404, 2409, 2648, 2650, 2661, 2806, 2882, 2900, 2943, 2996, 2998, 3006, 3038, 3041, 3298, 3396, 3411, 3429, 3434, 3507, 3545, 3552, 3712, 3774, 3794, 3838, 3841, 4060, 4208, 4256, 4269, 4310, 4323, 4517, 4689, 4786, 4787, 4976, 4998, 5029, 5159, 5270, 5347, 5409, 5555, 5615, 5653, 5656, 5674, 5708, 5709, 5998, 6081, 6153, 6165, 6166, 6167, 6169, 6171, 6172, 6277]

{'"Painfully injured" but no details',
 'Calf removed, not known if he survived ',
 'Details unknown, possibly a PROVOKED INCIDENT',
 'Involved a speared shark but no other details PROVOKED INCIDENT',
 'Leg severed mid-thigh, hand severed, arm above elbow and part of buttocks. Not known if he survived',
 'Man landed at Cape Levêque lighthouse in critical condition after being bitten by a shark. Not known if he survived.',
 'No details',
 'No details, "recovering in Darwin Hospital"',
 'No details, it was the year the first settlers came ashore in Holdfast Bay, Port Pirie',
 'No details, listed as PROVOKED INCIDENT',
 'No injury',
 'Severe bite to thigh. Not known if he survived',
 'Shark involvement not confirmed',
 'Unprovoked, but circumstances unknown',
 nan}

In [20]:
# Let's examine the case of M. There is only one entry classified as M.

case_M = shark_attacks.loc[shark_attacks['Fatal (Y/N)'] == 'M']
print(case_M)

# Printaremos também os índices referentes à entrada M. Futuramente retiraremos as linhas com base nessa lista.

case_M_list = list(case_M.index)
print(case_M_list)

# It seems it was only a laceration and the input was supposed to be N, not M. We will change it to 'N' (not fatal).

      Case Number         Date    Year      Type           Country      Area  \
285  2016.04.18.b  18-Apr-2016  2016.0  Provoked  FRENCH POLYNESIA  Tuamotos

         Location      Activity         Name Sex  Age  \
285  Makemo Atoll  Spearfishing  Hoata Iotua    M  22

                                                Injury Fatal (Y/N)     Time  \
285  Laceration to knee by speared shark PROVOKED I...           M  Morning

                 Species  Investigator or Source                     pdf  \
285  Grey reef shark, 2 m   TNTV News, 4/19/2016  2016.04.18.b-Iotua.pdf

                                          href formula  \
285  http://sharkattackfile.net/spreadsheets/pdf_di...

                                                  href Case Number.1  \
285  http://sharkattackfile.net/spreadsheets/pdf_di...  2016.04.18.b

    Case Number.2  original order Unnamed: 22 Unnamed: 23
285  2016.04.18.b          6018.0         NaN         NaN
[285]

In [21]:
# Showing all NaN in column Fatal (Y/N)

null_display_fatal = shark_attacks[shark_attacks['Fatal (Y/N)'].isnull() == True]
null_display_fatal

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0,NaN,NaN
76,2017.10.01,01-Oct-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,31,FATAL,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01,6227.0,NaN,NaN
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b,6224.0,NaN,NaN
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,25,"FATAL, but death was probably due to drowning",NaN,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b,6219.0,NaN,NaN
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Lacerations to left foot,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b,6205.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6307,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6309.0,NaN,NaN
6308,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6310.0,NaN,NaN
6309,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# Let's examine the case of NaN. There are many entries like this.
# We will reclassify the values of NaN based on columns 'Injury' and 'Species' since it seems the data entrier
# had put some keywords such as FATAL and Death on these columns and could lead us to improve our dataset.

# Let's define a function to apply to our dataset, where we classify the values in Fatal_adjusted based on
# columns 'Injury' and 'Species', when they do have the info 'death' or 'fatal'.

# WARNING: column Species is written with a space at the end = 'Species '

def fatal_classifier(row):
    
    """
    Essa função classificará em N ou Y com base nas strings ou lista de strings encontradas
    nas colunas Injury e Species.
    """
    
    if row['Fatal (Y/N)'] == ('Y' or 'y'):
        return 'Y'
    
    elif row['Fatal (Y/N)'] == ('N' or 'n'):
        return 'N'
        
    elif pd.isnull(row['Fatal (Y/N)']) == True: 
        
        try:            
            Injury_match_list = re.findall('[fFdD][aAeE][tTaA][aAtT][lLhH]', row['Injury'])    #variações de 'death' e 'fatal'
            Species_match_list = re.findall('[fFdD][aAeE][tTaA][aAtT][lLhH]', row['Species '])    #variações de 'death' e 'fatal'
            
            if  len(Injury_match_list + Species_match_list) == 0:
                return 'N'
    
            else:
                return 'Y'
        
        except:
            return 'Non available'
        
        
    else:
        return row['Fatal (Y/N)']

    
shark_attacks['Fatal_adjusted'] = shark_attacks.apply(fatal_classifier, axis=1)


#print(shark_attacks['Fatal_adjusted'] == shark_attacks['Fatal (Y/N)'])

null_display_fatal = shark_attacks[shark_attacks['Fatal (Y/N)'].isnull() == True]
null_display_fatal

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal_adjusted
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0,NaN,NaN,Non available
76,2017.10.01,01-Oct-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,31,FATAL,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01,6227.0,NaN,NaN,Y
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b,6224.0,NaN,NaN,N
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,25,"FATAL, but death was probably due to drowning",NaN,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b,6219.0,NaN,NaN,Non available
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Lacerations to left foot,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b,6205.0,NaN,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6307,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6309.0,NaN,NaN,Non available
6308,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6310.0,NaN,NaN,Non available
6309,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Non available
8702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Non available
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Non available

### Row dropping

In [23]:
# Let's drop the rows where Fatal_adjusted is Non available, through a list of indexes.

list_to_be_dropped = shark_attacks.loc[shark_attacks['Fatal_adjusted'] == 'Non available'].index

# Dropping the list of indexes
shark_attacks_v1 = shark_attacks.drop(index=list_to_be_dropped)

In [24]:
# Let's drop the case of 2017 (row 786).
case_2017_list = [786]

In [25]:
# Let's drop the case of UNKNOWNs ().
    # case_UNKNOWN_list
    
shark_attacks_v2 = shark_attacks_v1.drop(index=case_UNKNOWN_list)
shark_attacks_v3 = shark_attacks_v2.drop(index=case_2017_list)

### Row adjusting

In [26]:
# For M, we will update the row 285 for Fatal (Y/N) from M to N.

shark_attacks_v3.loc[285,'Fatal_adjusted'] = 'N'

# Checking the value update:

print(shark_attacks_v3.loc[285,'Fatal_adjusted'])

N

### Stripping spaces in Fatal_adjusted

In [27]:
def strip_spaces(x):
    return x.strip()    

shark_attacks_v3['Fatal_adjusted'] = shark_attacks_v3['Fatal_adjusted'].apply(strip_spaces)

In [28]:
set(shark_attacks_v3['Fatal_adjusted'])

{'N', 'Y', 'y'}

### Upper case all strings in Fatal_adjusted

In [29]:
shark_attacks_v3['Fatal_adjusted'] = shark_attacks_v3['Fatal_adjusted'].str.upper()

In [30]:
set(shark_attacks_v3['Fatal_adjusted'])

# We obtained a set containing only 'N' and 'Y' at the end.

{'N', 'Y'}

In [31]:
# The database updated:

shark_attacks_v3['Fatal_adjusted'].value_counts()

N    4580
Y    1620
Name: Fatal_adjusted, dtype: int64

### Total death rate (result)

In [32]:
death_rate = 1620/4580
print(f"""The total death rate for the time span was {death_rate*100}%. 
This number could be lower but hardly higher, since we dropped the columns where no conclusion could be drawn
and they were mostly about lacerations and such.""")

The total death rate for the time span was 35.37117903930131%.
This number could be lower but hardly higher, since we dropped the columns where no conclusion could be drawn
and they were mostly about lacerations and such.

In [33]:
shark_attacks_v3

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal_adjusted
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,N
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,N
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,N
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,N
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,Y
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,Y
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,Y
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,Y
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Y

## Data Cleaning: 'Activity'

### Checking uniques.

In [34]:
# Let's check the unique values of the column Activity.

print(set(shark_attacks['Activity']))

# Problematic: anedoctal(too many descriptions).
# We will have to categorize them better, maybe through bins.

{nan, 'Swimming near jetty', 'Floating or standing', 'Spearfishing / freediving', 'Standing on ship deck', 'Wreck of the Tweed', 'Sailing', 'Sea disaster, wreck of the sloop Sara', 'On life raft tethered to lifeboat. A seaman put hand over side to rinse a cup', 'Fishing (Drowned 2-Apr-2002)', 'Paddle Skiing', 'Boogie Boarding', 'Bathing alongside the American ship Thomas W. Sears', 'Surfing (sitting on his board)', 'Examining netted shark, that had been shot', 'Body boarding ', 'Air Disaster', 'Commercial fishing vessel, Ev-nn, struck object & sank. Ken Crosby and  Jame & Ann Dumas adrift on makeshift raft.', 'Snorkeling on surface', 'Swimming ashore from swamped 13-ft boat', "Fishing, stepped on hooked shark's head", 'Feeding prawns to captive sharks', 'Swept out to sea while fishing', 'Free diving & spearfishing ', 'Air disaster: crash of Air France Super Constellation ', 'Washing clothes on stairs', '17 Maldivians adrift in open boat for 31 days', 'Body boarding', 'Paddling a canoe', 'Surfing, collided with shark', 'Hookah diving for abalone (submerged)', 'Fishing from a small boat & put his hand in the water while holding a dead fish', 'Adrift on life raft', 'Reported swept away by waves while gathering opihi', 'Thrown overboard', 'British ship Macedon was thrown on her beam ends by a sudden squall', 'HBM Magpie foundered in a squall', 'Fell into the water', 'Killing  sharks', 'Scuba diving / culling lionfish', 'Fishing for bluefish', 'Greek steamship Lakonia caught fire, 98 of her 646 passengers, and 30 of her crew of 376 perished', 'Conducting research', 'Washing sand off a speared fish', '4 men were bathing', 'Surfing on air mattress', 'Standing', 'Moving shark from tuna vessel when boat rolled, placing both man & shark in chest-deep water', 'Water-skiing', 'Hauling dead shark aboard, when another shark leapt out of the water & bit him', 'Skindiving for abalone (but at surface)', 'Sunbathing on beach when he saw child being attacked by the shark', 'Spearfishing (but treading water on the surface)', 'Lifesaving drill', 'Fell overboard?', 'Fishing / standing in waist deep water', 'Floating ', 'British patrol boat 1250-ton HMS  Valerian foundered in a hurricane', 'Unknown, their unoccupied yawlboat was recovered', 'Playing on rock, slipped & fell into the water', 'Fishing for snoek & yellowtail', 'Walking out of the water after surfing', 'Floating near boat & observing bioluminesce', 'Spearfishing or fishing', 'Sculling', '3,909-ton Panamanian freighter Chieh Lee sank in a typhoon', 'Bathing/Swimming', 'Standing / Bathing', 'Swimming to shore after boat capsized by a squall', 'Surfing, pushing board ashore', 'Jumping in swells', 'Pleasure boating', 'Swimming / Wading', 'Fleeing across a river', 'Gathering fish stunned by dynamite', 'Fishing for lobsters', 'Swimming from naptha launch after a day of fishing', 'Paddling on surfboard or body board', 'Diving, recovering fish killed by dynamite', 'Dragging stranded shark into deeper water', 'Among 31 survivors of crew from the sampan Fukulya Maru (which reached Thursday Island in rowing boat) was a man whose arm had been bitten off by shark. The sampan wrecked west of McArthur island ', 'Boogie-boarding / swimming', '1446-ton Norwegian barque Errol, bound from Peru to Newcastle with 22 on board wrecked. Survivors shelterd on the wreck of the Annasona. Subsequently the Master, his wife & 4 children perished along with several crew. Survivors (5) were rescued 7/12/1909', 'Standing in waist-deep water, helping his father tend a gill net containing dead fish', 'Attempting to rescue an injured & beached shark', 'Rescuing seaman after ship sunk by German raider', 'The MV Dona Marilyn sank in Typhoon Unsang with the loss of 389 lives', 'SS Ethel Skakel foundered in Central America Hurricane of 1941', 'Fishing, speared shark upset canoe & man fell in water', 'Survived US Naval aircraft crash, climbing onboard rescue vessel when he fell back into sea ', 'Swimming to shore from boat or kayak', 'Wading', 'She was on a ship that was torpedoes & was in the water awaiting rescue', 'Attempting to rescue drowning man', 'yachting accident', 'Washing his pig in preparation for a religious ceremony', 'Skin diving ', 'Spear fishing, removing fish from spear', 'Windsurfing (urinating on his board)', 'Diving for trochus , but swimming on surface', 'Fell from cliff while fishing & disappeared in strong current', 'Kite boarding', 'Scallop diving on hookah', 'boat from ship Josephine capsized in squall', "Sitting in bow of her father's 5 m boat", 'Survived crash of two-engine  C-46 transport plane carrying 62 migrant workers from Puerto Rico to USA ', 'Spearfishing, shark grabbed his white t-shirt and towed him ', 'Free diving, working on U/W scenes for motion picture', 'Swimming with mask & snorkel', 'Bather', 'Floating with life preserver after his boat foundered', 'Standing on sandbank', 'Swimming after boat became disabled', "63' fishing boat Sno' Bay foundered", 'Wading, netting fish', 'Killing a shark', 'Swimming alongside the SS Kearsarge', 'Hand lining for shad', 'Hardhat diving ', 'Fishing from shore', 'Standing, collecting bananas', 'Dry shelling', 'Hiking on the beach', 'Arsinoe, a French tanker', 'Swimming / shipwreck', 'Fell overboard from sponge vessel', "Lying on the bottom of a 16' dinghy", 'Shark fishing, knocked overboard', 'Skindiving for specimens', 'Fishing, casting in the surf', 'Fishing with a cast net', 'Observing a shark feeding on a carcass of a humpback whale', 'Fishing, holding fish', 'Shooting sharks ', 'The 500-ton coastal trader Polurrian foundered ', 'Helping men land a shark', 'Diving for lobsters', 'Swimming / jumping off a jetty', 'Longling fishing', 'Surfing (pneumatic surfboard)', 'Fishing, one of three fishermen swept into the sea by a large wave ', 'Swimming after their boat capsized', 'Human head found in shark caught by British steamer Syria', 'Fishing for shrimp', 'Filming', "Scientific research (Dr. Sonny Gruber's student)", 'Attempting to set underwater endurance record', 'Trailing hand in the water', 'Sittting in water with his child', 'Attempting to lasso a shark', 'Surf fishing in waist-deep water', 'The cutter yacht Cutty Sark sank', "Crouching in 2' of water", 'Batin', 'Swimming from camp', 'Wreck of the 1308-ton Norwegian ship Auckland', 'Swimming with speared fish', 'A 75-ton  Japanese fishing ship was sunk by  Chinese Nationalist gunboat, shipwrecked men were clinging to debris', 'Kayaking or Wave skiing', 'Removing shark from a net', 'Scuba diving for abalone (at surface)', 'U-177 torpedoed & sank the troopship Nova Scotia', 'Surfing (or sailboarding)', 'Standing, stepped on shark', 'Scooping prawns', 'Wreck of the Aphrodite', 'preparing to go skin diving', 'Riding floatation device', 'Washing his feet', 'Scuba diving in aquarium tank', 'Diving, feeding sharks', 'Splashing', 'Hookah diving for sea urchins', 'Body surfing, stood up on sandbar', 'The schooner Elizabeth, bound from Bluefields, Nicaragua to the river port of San Carlos foundered', "Overcome by CO fumes, fell overboard from 36' fishing cruiser & prop slashed arm", 'A father bathing his smallest daughter when the shark bumped her out of his arms and carried her into deep water', 'Climbing back on ship', 'Fishing from surfski', 'Boat stopped to repair electric pump', 'Fishing in knee-deep water', 'Skimboarding', 'SCUBA Diving', 'Stand-Up Paddleboarding', 'Swimming, when caught in heavy seas', 'Flying Fortress bomber aircraft went down after daytime raid on Naples. He was swimming on the surface', 'Sinking of the ferryboat Bongbong 1', 'Hard hat diving', 'Standing, holding shark pup', 'S2F-1 airplane crashed immediately after carrier take-off', 'Grabbing shark for a selfie', 'Reviving a sedated shark', 'Paddling rescue ski', "Sitting in 3' of water", 'Free diving, collecting shells', 'Diving, but on the surface when bitten by the shark', 'Dived from inner-tube', 'Washed off freighter Huncliff by a freak wave', 'Free diving / spearfishing (resting on the surface)', 'Canoeing', 'The British steamer Caribbee foundered', 'Scuba diving & feeding fish', 'Diving ', 'cargo ship Southern Isle sank at 04h00', 'Foundering of the Israeli freighter Mezada', 'Cutter capsized', 'Retrieving bait box that had fallen overboard', 'Playing in the surf', 'Net fishing, fell into the water', 'Floating on a raft', 'Swimming after being washed overboard', 'Attempting to rescue crew after whale upset their boat', 'Suicide', 'Free diving with a pod of dolphins', '3 men & 2 boys picked up wearing life jackets and with inner tube', 'Swimming near shore', 'Bodyboarding', 'The SS Potlach was torpedoed & sunk by the U-153 on 27-Jun-1942. ', 'Wading after stray fish from seine netter\x92s catch', 'Hunting seals', 'Kayaking', 'Sponge diving', 'Snorkeling \x96 hunting crayfish and abalone', 'Bathing', 'Reaching for life preserver', 'Pulling anchor', 'Hunting sharks', 'Free diving with goggles', 'Swimming on surface', 'Diving for beche-de-mer', 'Boeing 757 enroute from Porta Plata plunged into the sea', 'Swimming underneath house on pilings', 'Swimming on sandbar adjacent to channel', 'Swimming in section of river used for washing clothes & cooking utensils', 'Sitting in shallows', 'Pearl diving from lugger', 'Abalone diving using Hookah (near calving whales)', 'Jumped or fell overboard', 'Kayaking / Fishing', 'Sinking of the dredge World Atlas', 'Bodysurfing', '"Flying Tiger" transport plane went down with 5 men onboard', 'Wading or swimming', 'Attempting to rescue a shark', 'Swimming out to porpoises ', 'Fishing for white shark', 'Fishing (rod & line)', 'Painting a ship', 'Playing', 'Diving for sea urchins', 'Collecting fish in military trap when bitten by captured shark that had been shot by soldiers with Garten', 'Harpooned shark', 'Trochus diving, but floating on surface', 'Free diving & spearfishing (ascending)', 'Wading to dinghy, carrying his son', 'Catching sharks under government contract', 'Swimming ashore from a "filibuster"', 'Shark fishing on the Don Agustín-VI. ', 'Fishing  (trawling)', 'Spearfishing, but walking carrying fish on end of speargun', 'Swimming in pool formed by construction of a wharf', 'Fell overboard from steamship Rio Grande', 'Jumped off surfboard & landed on the shark', 'Body surfing / treading water', 'Fishing (trolling)', 'Free diving for lobster', 'Jumped overboard and swimming', 'On boat, preparing to dive', 'Swimming with board', "Diving for trochus  from dinghy when seized by shark 6' below the surface", 'Attempting to retreive a dinghy', 'Fell overboard from the Sobella', 'A 210-ton brig was sunk by a Japanese submarine. Some of the survivors were machine-gunned & some were taken by sharks', 'Playing in knee-deep water', 'Gaffing & attempting to bring onboard a harpooned shark', "Zosimo & his son, Jeffrey Popa, failed to return from overnight fishing trip in a 14' boat, Boat apparently sank, debris recovered but his son & boat were never found", 'Scuba diving, but swimming on surface', 'Fishing from boat, Kaimamla', 'Surfing, paddling shorewards', 'Washed off catamaran in the surf', 'Feeding stingrays?', 'Scuba diving for abalone', 'Attempting to land a boat from the Hinemoa', 'Swimming outside the safety enclosure attempting to retrieve a tennis ball drifting toward midstream ', "40' fishing boat sank", 'Adrift after ditching plane in the sea', 'Standing in inner tube', 'Floating on air mattress', 'Stamding', 'Standing in waist-deep water', 'Surf-skiing', 'Finning the shark', 'The 3540-ton Alfonso Penna was torpedoed & sunk by the Italian submarine Barbarigo', 'Board sailing', 'Scuba diving (but on surface)', 'Floating in creek', 'Gigging for flounder', 'Scuba diving & spearfishing', 'Diving alongsidethe steamship Ranelagh ', 'Crawling', 'Swimming. Passer-by, Len Bedford, heard him shriek , saw shark leap from the water & swimmer disappeared', 'Diving & force-feeding the shark', "Fishing with hand net in 2' of water", 'Paddling a surfboat', 'Murdered', 'Bathing with her mother', 'Abalone diving using Hookah (resting on the surface)', 'Jumped overboard ', 'Cargo ship Dara sank after collision with another ship during a severe storm', 'Surfing, but treading water', 'Oyster fishing', 'The passenger ship Kapuna was run down the ore carrier Ada Melmore', 'Surfing, but standing in water alongside board', 'Paddle-boarding', 'Scuba diving & spearfishing ', 'Fishing, tossing netted shark onboard', 'Goggle-diving for seaweeds, but standing in water', 'Washed off raft', 'Bending over', 'Slipped off rocks and fell into the water', 'Fishing for bottom fish', 'Canoe capsized with 10 occupants, 8 survived,  Hamilton swam off to seek help', 'Attempting to rescue woman seized by shark', 'Diving off pier & treading water', 'Standing in knee-deep water', 'wreck of the State Oil Company ship Permina', 'Air Disaster - Piper aircraft crashed into the sea, killing all on board', 'Surf fishing, wading ', 'Splashing in water ', 'Oystering', "Accidentally stood on hooked shark's tail before attempting to gut it ", 'Jumped overboard while intoxicated', 'Air disaster', 'Tandem surfing', 'Boat with 5 men capsized while returning to the Amerique', 'Schooner sank during a storm', 'Swimming from capsized pirogue', 'Anti-sabotage night dive exercise alongside destroyer (Scuba diving)', 'Feeding a shark', 'Picking up shark by the tail', 'Collecting beche-de-mer', 'Small vessel with 13 men on board capsized crossing the bar and 6 men drowned.  The 7 survivors were swimming to shore', 'Removing hook from shark', 'Torpedoed & burning British  light cruiser with a crew of 450 men', 'During "an exhibition" he was tied in sack & thrown overboard ', 'Ascending from a dive', 'Dived overboard to check propeller of US Navy motor torpedo boat', 'Air disaster. Flash Airlines Boeing 737 crashed into the Red Sea', 'Fell overboard from the steamship Chala', 'Wading to shore from his boat', 'Snorkeling, possibly holding a fish', 'Yacht race', 'Holding onto an inflatable boat', 'Hookah diving (submerged)', 'Swept off deck of S.S.Frontenac enroute from West Indies to US', 'Fell overboard from the ship Gem', "Standing on landed shark's tail", 'Lifeboat capsized', "Skin diving. Grabbed shark's tail; shark turned & grabbed diver's ankle & began towing him to deep water", 'Wading, fishing for flounder', 'Adrift on refugee raft', '3-masted steel barque Glenbank foundered during a cyclone', 'boat from the Austrian ship Elizabeth', 'U.S. Airforce C124 enroute from Hickham Air Base to Japan went down. The 3 survivors fashioned raft from mailbags  & were rescued 3 days after the crash.', 'The 168-ton Belmore foundered in heavy seas', 'Swimming, after boat swamped', 'Bringing hooked, harpooned shark onboard boat', 'Bathing in waist-deep water', 'Kite-Boarding', 'Launching rowboat through the surf', 'Fishing, boat capsized', 'Surf-fishing', 'Parachuted into Pacific', 'Wading near a fishing net', 'Scuba diving ', 'Swimming / treading water', 'Spearfishing & had just speared a ulua', 'The 240-ton motor vessel Pilar II with 100 people on board capsized in high winds & rough seas', 'Fell from wharf into water & attacked immediately', 'Crossing the bay at the ford', 'Attempting to drive shark from area', "Fishing from 32' boat", 'Netting pilchards', 'Fishing for prawns', 'Japanese POW ship Arisan Maru with 1800 American prisoners of war on board bound for slave labor camps was torpedoed by an American submarine', 'Ejected from F3H-2 aircraft ', 'Surf skiing', 'Fishing for rock lobster', 'Plane forced down, 3 men on rubber life raft. Put hand over side to feel drift of boat ', 'Sitting on side of dinghy mending a net', 'Crossing the river mouth', 'When  a deckhand  jumped overboard, McIver dived after him with a rescue line.', 'Fishing, fell from rocks & disappeared', 'Playing with a frisbee in the shallows', 'Fishing for kob', 'Dropping anchor', 'Floating on raft', 'Standing alongside surfboard', 'Swimming near life raft', "Bathing in 3' to 4' of water", 'Lying in 2 feet of water', 'Fishing / Wading', 'Rowing a dinghy', 'Conch diver', "Bathing in 5' of water", 'Line fishing from Lakotoi, saw shoal of fish, dived overboard, had speared second fish & surfaced for air', 'Spearfishing, but standing in the water', 'Washed into sea while picking opihi', 'Fell overboard from the Malacca', 'Fishing, slipped on rocks & fell into sea', 'Filming a documentary', 'Hand feeding sharks', 'Free diving / photography, kneeling on sand', 'The steamships Thingvalla and Geiser collided', 'Gloucester fishing schooner run down', 'boat capsized during filming', 'Swimming to shore from capsized kayak', 'Diving for trochus from lugger', 'Sitting on gunwale of boat', 'Canoe with 3 men onboard sank', 'Spearfishing, shot shark, hauled it onto boat', 'Landing hooked shark in boat', 'Jumped into the water', 'Capsized fishing boat', 'Walking in shallows', 'NSB Meshing', 'Sitting', 'Fishing schooner Jose Luis foundered', 'Boogie boarding', 'Netting sharks', 'Free diving, surveying a pipeline & examing cathodes under jetty', 'Freediving', 'Free diving / Spearfishing', 'Attacked shark with fists', 'Free-diving', 'Kayaking ', 'Fishing, hauling in net, shark in net', 'Fell into water while attempting to boat a swordfish', 'Lobster fishing', 'Bathing near whaling ship (bark A. R. Tucker of New Bedford, Massachusetts)', 'Spearing a shark', 'Bathing in 2 feet of water', 'Fishing for albacore', 'Surfing / treading water', 'Sea Disaster Sinking of ferryboat Christina', 'Fishing for white sharks', 'Playing with an air mattress', 'Washed overboard into school of fish', 'Swimming with dog near canning factory', 'Swimming with motor tube', 'Swimming /  Whale Watching', 'Dynamiting fish', ' ', 'Netting menhaden, sharks caught in net', 'Spearfishing, had fish on his spear', 'Fell overboard, hanging onto lifebuoy', 'Fishing from Surfboard', 'Aircraft crashed into sea', 'British ship, Britannia,  was loading lumber. He was bathing', 'Swimming with goggles', 'Swimming, using bundles of sticks as raft', 'Boat of the Resolution capsized in the breakers', 'Swimming close to wharf', 'Swimming to shore after a squall  capsized their motorized shark fishing boat', 'Spearing fish', 'Jumped overboard from Norwegian steamship Venator', 'Swimming / snorkeling', 'Steamer Durao struck rock & filled, boats capsized, passengers & crew tried to swim to shore', 'Swimming in fish tank', 'Free diving, hunting crayfish', 'American cruiser Indianapolis torpedoed & sunk by the Japanese submarine I-58', 'Wreck of the Union Steamship Company 982-ton iron steamer Kafir', 'Spearfishing, pulled shark\x92s tail', 'Adrift after wave swamped engine', 'Inebriated, woke from sleep and fell off deck into the water ', 'Spearfishing on scuba & transferring fish onto a stringer', 'Free diving for abalone from Zodiac (submerged)', 'Swimming or paddle boarding', 'Ferry capsized', 'Italian liner Principessa Mafalda sank', 'Fishing, standing in waist-deep water', 'Fishing, hauling in fishing gear', 'Testing anti-shark cage', 'Body boarding or surfing', 'Boogie boarding, kicked at object in the water', 'Fishing, setting nets', 'Boat, with 42 passengers onboard, capsized in rough seas', 'Standing or boogie boardin', 'Anti-Aircraft cruiser USS Atlanta (CL,-05) travelling in convoy after the Battle of Midway, encountered a Japanese flotilla  (Battle of Guadalcanal) &, heavily damaged by gunfire, she was lost off Lunga Point. Victim was swimming when bitten.', 'The 2379-ton French steamer La Seyne collied with British steamer Onda & sank in minutes. Passengers jumped overboard expecting to be picked up by Onda\x92s boats', 'Working near fish traps', 'Free diving for shell', 'Clinging to shipwrecked junk', 'Bitten while cutting shark from net', 'Diving for trochus shell', "Filming 5' blue shark", 'In waist-deep water', 'Fishing, on a boat', 'Swimming, naked', 'Pearl diving, but standing in the water', 'Fishing, sitting in stern of s

In [35]:
print(f"""

We will base this on the following sources:

https://en.wikipedia.org/wiki/List_of_water_sports
https://www.themost10.com/popular-water-sports/

- Fishing: Fishing / Spearfishing / Deep sea fishing / Big game fishing
- Diving: Diving / Scuba Diving / Snorkeling / Freediving
- Surfing: Surfing
- Swimming: Swimming
- Parasailing: Parasailing
- Boats: Kayaking / Canoeing / Rafting / Boating
- Skiing: Jet Skiing / Water Skiing
- Wake: Wakeboarding / Wakesurfing
- Kite: Kitesurfing / Kiteboarding
- Motorized boats: Yachting / Ship
- Other activities

...and finally...

- Shark feeding

""")

We will base this on the following sources:

https://en.wikipedia.org/wiki/List_of_water_sports
https://www.themost10.com/popular-water-sports/

- Fishing: Fishing / Spearfishing / Deep sea fishing / Big game fishing
- Diving: Diving / Scuba Diving / Snorkeling / Freediving
- Surfing: Surfing
- Swimming: Swimming
- Parasailing: Parasailing
- Boats: Kayaking / Canoeing / Rafting / Boating
- Skiing: Jet Skiing / Water Skiing
- Wake: Wakeboarding / Wakesurfing
- Kite: Kitesurfing / Kiteboarding
- Motorized boats: Yachting / Ship
- Other activities

...and finally...

- Shark feeding

### Classifying

In [36]:
shark_attacks['Activity'] = shark_attacks['Activity'].astype(str)

def activity_classifier(row):
    """
    This function will classify the rows present in columns 'Activity' based on a list of strings set before.  
    """
    
    feeding_match_list = re.findall('[fF][eE][eE[dD]\w*', row['Activity'])
    fishing_match_list = re.findall('[fF][iI][sS][hH][iI]\w*', row['Activity'])
    diving_match_list = re.findall('[dD][iI][vV]\w*', row['Activity'])
    surfing_match_list = re.findall('[sS][uU][rR][fF]\w*', row['Activity'])
    swimming_match_list = re.findall('[sS][wW][iI][mM]\w*', row['Activity'])
    parasailing_match_list = re.findall('[pP][aA][rR][aA][sS][aA][iI][lL]\w*', row['Activity'])
    skiing_match_list = re.findall('[sS][kK][iI]\w*', row['Activity'])
    wake_match_list = re.findall('[wW][aA][kK][eE]\w*', row['Activity'])
    kite_match_list = re.findall('[kK][iI][tT][eE]\w*', row['Activity'])
    boating_match_list = re.findall('[kKcCrRbB][aAoO][yYnNfFaA][aAoOtT][eE]?\w*', row['Activity'])
    motorized_match_list = re.findall('[yYsS][aAhH][tTiI][cCpP][hH]?\w*', row['Activity'])
    
    if  len(feeding_match_list) != 0:
        return feeding_match_list[0]
    
    elif len(fishing_match_list) != 0:
        return fishing_match_list[0]
    
    elif  len(diving_match_list) != 0:
        return diving_match_list[0]
        
    elif len(surfing_match_list) != 0:
        return surfing_match_list[0]
        
    elif len(swimming_match_list) != 0:
        return swimming_match_list[0]
    
    elif len(parasailing_match_list) != 0:
        return parasailing_match_list[0]
    
    elif len(skiing_match_list) != 0:
        return skiing_match_list[0]
    
    elif len(wake_match_list) !=0:
        return wake_match_list[0]
    
    elif len(kite_match_list) !=0:
        return kite_match_list[0]
    
    elif len(boating_match_list) != 0:
        return boating_match_list[0]
    
    elif len(motorized_match_list) != 0:
        return motorized_match_list[0]
    
    else:
        return 'Others'
    
    
shark_attacks_v3['Activity_adjusted'] = shark_attacks.apply(activity_classifier, axis = 1)

shark_attacks_v3

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal_adjusted,Activity_adjusted
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,N,Others
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,N,Others
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,N,Surfing
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,N,Surfing
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,N,diving
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,Y,Diving
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,Y,diving
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,Y,Swimming
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,Y,Others
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Y,Swimming

In [37]:
set(shark_attacks_v3['Activity_adjusted'])

{'Boat',
 'Boating',
 'Canada',
 'Canoe',
 'Canoeing',
 'Dived',
 'Diving',
 'Feeding',
 'Feeling',
 'Fishing',
 'Fishingat',
 'Kayaking',
 'Kite',
 'Kiteboarding',
 'Others',
 'Raytheon',
 'Royal',
 'Ship',
 'Shipwreck',
 'Shipwrecked',
 'Skiing',
 'Skimboarding',
 'Surf',
 'Surfing',
 'Surfng',
 'Swimming',
 'Wakeboarding',
 'banana',
 'bananas',
 'boat',
 'boating',
 'boats',
 'caft',
 'canoe',
 'canoeing',
 'canoes',
 'containing',
 'contract',
 'dive',
 'dived',
 'diver',
 'divers',
 'divians',
 'diving',
 'fed',
 'feeding',
 'feel',
 'feet',
 'fishing',
 'fishingat',
 'kite',
 'raft',
 'rafts',
 'rant',
 'roat',
 'ronaut',
 'rontenac',
 'ship',
 'shipmate',
 'shipmates',
 'ships',
 'shipwreck',
 'shipwrecked',
 'ski',
 'skiff',
 'skiing',
 'surf',
 'surface',
 'surfboard',
 'surfboat',
 'surfing',
 'surfmat',
 'swim',
 'swimming',
 'swimmng'}

In [38]:
"""
It is clear that we reduced the problem to some categories. Let's refine it.
"""

shark_attacks['Activity'] = shark_attacks['Activity'].astype(str).str.lower()

def activity_classifier(row):
    """
    This function will classify the rows present in columns 'Activity' based on a list of strings set before.  
    """
    
    feeding_match_list = re.findall('[f][e][e][d].*[s][h][a]', row['Activity'])
    fishing_match_list = re.findall('[f][i][s][h][i]', row['Activity'])
    diving_match_list = re.findall('[d][i][v]', row['Activity'])
    surfing_match_list = re.findall('[s][u][r][f]', row['Activity'])
    swimming_match_list = re.findall('[s][w][i][m]', row['Activity'])
    parasailing_match_list = re.findall('[p][a][r][a][s][a][i][l]', row['Activity'])
    skiing_match_list = re.findall('[s][k][i]', row['Activity'])
    wake_match_list = re.findall('[w][a][k][e]', row['Activity'])
    kite_match_list = re.findall('[k][i][t][e]', row['Activity'])
    boating_match_list = re.findall('[kcrb][ao][ynfa][aot]', row['Activity'])
    motorized_match_list = re.findall('[ys][ah][ti][cp][h]?', row['Activity'])
    
    if  len(feeding_match_list) != 0:
        return feeding_match_list[0]
    
    elif len(fishing_match_list) != 0:
        return fishing_match_list[0]
    
    elif  len(diving_match_list) != 0:
        return diving_match_list[0]
        
    elif len(surfing_match_list) != 0:
        return surfing_match_list[0]
        
    elif len(swimming_match_list) != 0:
        return swimming_match_list[0]
    
    elif len(parasailing_match_list) != 0:
        return parasailing_match_list[0]
    
    elif len(skiing_match_list) != 0:
        return skiing_match_list[0]
    
    elif len(wake_match_list) !=0:
        return wake_match_list[0]
    
    elif len(kite_match_list) !=0:
        return kite_match_list[0]
    
    elif len(boating_match_list) != 0:
        return boating_match_list[0]
    
    elif len(motorized_match_list) != 0:
        return motorized_match_list[0]
    
    else:
        return 'other activities'

    
shark_attacks_v3['Activity_adjusted'] = shark_attacks.apply(activity_classifier, axis = 1)

shark_attacks_v3

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal_adjusted,Activity_adjusted
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,N,other activities
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,N,other activities
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,N,surf
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,N,surf
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,N,div
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,Y,div
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,Y,div
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,Y,swim
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,Y,other activities
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Y,swim

In [39]:
set(shark_attacks_v3['Activity_adjusted'])

{'bana',
 'boat',
 'caft',
 'cana',
 'cano',
 'cont',
 'div',
 "feeding 2.5' to 5\x92 sha",
 'feeding a sha',
 'feeding captive sha',
 'feeding mullet to sha',
 'feeding prawns to captive sha',
 'feeding sha',
 'feeding the sha',
 'fishi',
 'kaya',
 'kite',
 'other activities',
 'raft',
 'rant',
 'rayt',
 'roat',
 'rona',
 'ront',
 'roya',
 'ship',
 'ski',
 'surf',
 'swim',
 'wake'}

In [40]:
"""
Now that we narrowed down, we will classify them.
"""

shark_attacks['Activity'] = shark_attacks['Activity'].astype(str).str.lower()

def activity_classifier(row):
    """
    This function will classify the rows present in columns 'Activity' based on a list of strings set before.  
    """
    
    feeding_match_list = re.findall('[f][e][e[d].*[s][h][a]', row['Activity'])
    fishing_match_list = re.findall('[f][i][s][h][i]', row['Activity'])
    diving_match_list = re.findall('[d][i][v]', row['Activity'])
    surfing_match_list = re.findall('[s][u][r][f]', row['Activity'])
    swimming_match_list = re.findall('[s][w][i][m]', row['Activity'])
    parasailing_match_list = re.findall('[p][a][r][a][s][a][i][l]', row['Activity'])
    skiing_match_list = re.findall('[s][k][i]', row['Activity'])
    wake_match_list = re.findall('[w][a][k][e]', row['Activity'])
    kite_match_list = re.findall('[k][i][t][e]', row['Activity'])
    boating_match_list = re.findall('[kcrb][ao][ynfa][aot]', row['Activity'])
    motorized_match_list = re.findall('[ys][ah][ti][cp][h]?', row['Activity'])
    
    if  len(feeding_match_list) != 0:
        return 'feeding'
    
    elif len(fishing_match_list) != 0:
        return 'fishing'
                
    elif  len(diving_match_list) != 0:
        return 'diving'
        
    elif len(surfing_match_list) != 0:
        return 'surfing'
        
    elif len(swimming_match_list) != 0:
        return 'swimming'
    
    elif len(parasailing_match_list) != 0:
        return 'parasailing'
    
    elif len(skiing_match_list) != 0:
        return 'skiing'
    
    elif len(wake_match_list) !=0:
        return 'wake'
    
    elif len(kite_match_list) !=0:
        return 'kite'
    
    elif len(boating_match_list) != 0:
        return 'boating'
    
    elif len(motorized_match_list) != 0:
        return 'yatching/ship'
    
    else:
        return 'other activities'

    
shark_attacks_v3['Activity_adjusted'] = shark_attacks.apply(activity_classifier, axis = 1)

shark_attacks_v3

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal_adjusted,Activity_adjusted
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,N,other activities
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,N,other activities
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,N,surfing
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,N,surfing
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,N,diving
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,Y,diving
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,Y,diving
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,Y,swimming
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,Y,other activities
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Y,swimming

In [41]:
set(shark_attacks_v3['Activity_adjusted'])

{'boating',
 'diving',
 'feeding',
 'fishing',
 'kite',
 'other activities',
 'skiing',
 'surfing',
 'swimming',
 'wake',
 'yatching/ship'}

In [42]:
# Let's check the results of the classification.

shark_attacks_v3[shark_attacks_v3['Activity_adjusted'] == 'feeding']

# In general it's pretty good.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal_adjusted,Activity_adjusted
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,2018.05.24,6293.0,NaN,NaN,N,feeding
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Dugong Bay,Feeding sharks,Melisa Brunning,F,34,Shallow lacerations to finger PROVOKED INCIDENT,N,NaN,"Tawny nurse shark, 2m","Perth Now, 6/30/2018",2018.05.00-Brunning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.00,2018.05.00,6289.0,NaN,NaN,N,feeding
132,2017.06.14.R,Reported 14-Jun-2017,2017.0,Unprovoked,BAHAMAS,NaN,NaN,Feeding sharks,Carly,F,NaN,Fingernail pulled off,N,NaN,NaN,"AOL.UK, 6/14/2017",2017.06.14.R-Carly.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.14.R,2017.06.14.R,6171.0,NaN,NaN,N,feeding
140,2017.05.28,28-May-2017,2017.0,Unprovoked,USA,Florida,Off Jupiter,Feeding sharks,Randy Jordan,M,NaN,Lacerations to right arm,N,Morning,Tiger shark,"M. Michaelson, GSAF",2017.05.28-Jordan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.05.28,2017.05.28,6163.0,NaN,NaN,N,feeding
442,2015.03.16,16-Mar-2015,2015.0,Unprovoked,FRENCH POLYNESIA,Bora Bora,Anau,Hand feeding sharks,male,M,9,Hand bitten,N,10h00,Blacktip shark,"Radio1, 3/16/2015",2015.03.16-Bora-Bora.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.03.16,2015.03.16,5861.0,NaN,NaN,N,feeding
811,2012.03.06.a,06-Mar-2012,2012.0,Provoked,AUSTRALIA,Victoria,"Shipwreck Cove, Melbourne Aquarium","Diving, feeding sharks",female,F,34,Superficial lacerations to right side of face ...,N,11h30,"Tawny nurse shark, 40cm","The Age, 3/6/2012",2012.03.06.a-MelbourneAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.03.06.a,2012.03.06.a,5492.0,NaN,NaN,N,feeding
2073,2000.02.14,14-Feb-2000,2000.0,Provoked,ENGLAND,Worcestershire,The Fountain Pub in Tenbury Wells,Feeding prawns to captive sharks,"Paul Smith, a chef",M,NaN,Fingers bitten PROVOKED INCIDENT,N,NaN,"Miami, a 60 cm blacktip shark and two 60 cm b...","The Sun (London), 2/17/2000",2000.02.14-Smith.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.02.14,2000.02.14,4230.0,NaN,NaN,N,feeding
2701,1989.00.00.b,1989,1989.0,Unprovoked,PAPUA NEW GUINEA,New Ireland,Kavieng,"Scuba diving, hand feeding sharks",Dinah Halstead,F,NaN,Thigh & calf bitten,N,NaN,7' silvertip shark,"S. Waterman, GSAF",1989.00.00.b-Halstead,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1989.00.00.b,1989.00.00.b,3602.0,NaN,NaN,N,feeding
3200,1975.12.02,02-Dec-1975,1975.0,Provoked,AUSTRALIA,New South Wales,"Porpoise Pool, Tweed Heads",Filming & feeding captive sharks,John Strand,M,35,Tooth mark in left elbow PROVOKED INCIDENT,N,NaN,"Grey nurse shark, 10'","J. Green, p.36",1975.12.02-Strand.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.12.02,1975.12.02,3103.0,NaN,NaN,N,feeding
3235,1975.03.13,13-Mar-1975,1975.0,Provoked,AUSTRALIA,Queensland,Southport Aquarium,Diving & force-feeding the shark,William Hookway,NaN,18,Laceration to thigh by captive shark PROVOKED ...,N,NaN,"Bronze whaler shark, 6'","The Age, 3/14/1975",1975.03.13-Hookway.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.03.13,1975.03.13,3068.0,NaN,NaN,N,feeding
3446,1968.12.26,26-Dec-1968,1968.0,Provoked,AUSTRALIA,New South Wales,"Marineland Aquarium, Manley, Sydney",Feeding mullet to sharks,Peter Jones,M,27,Laceration to finger by a captive shark PROVOK...,N,Morning,"Grey nurse shark, 10'","The Age, 12/27/1968",1968.12.26-Jones.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1968.12.26,1968.12.26,2857.0,NaN,NaN,N,feeding
3527,1967.05.09,09-May-1967,1967.0,Provoked,AUSTRALIA,NaN,Aquarium,Feeding a shark,Rod Stanley,M,22,Recorded as PROVOKED INCIDENT,N,Afternoon,Grey nurse shark,H.D.Baldridge (1994) SAF Case #1536,1967.05.09-NV-Stanley.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1967.05.09,1967.05.09,2776.0,NaN,NaN,N,feeding
4049,1959.11.10,10-Nov-1959,1959.0,Unprovoked,USA,California,"Near Paradise Cove, Malibu, Los Angeles County",Swimming at surface through school of feeding ...,Duffie Fryling,M,21,Forearm bitten,N,10h30 or 13h30,"Blue shark, 1.5 m [5']","D. Miller & R. Collier; R. Collier, pp.26-27; ...",1959.11.10-Fryling_Collier.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1959.11.10,1959.11.10,2254.0,NaN,NaN,N,feeding
4720,1942.00.00.k,1942,1942.0,Sea Disaster,INDONESIA,East Java,Surabaya,Captured Allied soldiers were squeezed into 3'...,200 soldiers,M,NaN,"General Imamura, Commander in Chief of Japanes...",Y,NaN,NaN,G. Duncan,1942.00.00.k-PigBasketAtrocity.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.00.00.k,1942.00.00.k,1583.0,NaN,NaN,Y,feeding
5131,1927.02.14,14-Feb-1927,1927.0,Provoked,NICARAGUA,Salinas Bay,"A shark was caught, its head severed from body...",Feeling the sharks teeth,a sailor,M,NaN,"Sharkss jaws snapped shut, lacerating his rig...",N,NaN,NaN,"G.A. Llano, p.178",1927.02.14-sailor.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.02.14,1927.02.14,1172.0,NaN,NaN,N,feeding

## Conclusion

In [43]:
# We managed to filter down all the entries into feeding sharks.
# Now we can divide by the number of valid total entries and get the % shark incidents.

feeding = shark_attacks_v3[shark_attacks_v3['Activity_adjusted'] == 'feeding'].shape[0]

feeding_attacks_perc = round(feeding/6200*100, 2)

print(f'The percentage share of attacks while feeding sharks during the timespan is {feeding_attacks_perc}%.')

The percentage share of attacks while feeding sharks during the timespan is 0.24%.

In [45]:
# In parallel, the % of attacks during diving is:

diving = shark_attacks_v3[shark_attacks_v3['Activity_adjusted'] == 'diving'].shape[0]

diving_attacks_perc = round(diving/6200*100, 2)

print(f'The percentage share of attacks while feeding sharks during the timespan is {diving_attacks_perc}%.')
print("Therefore, the chance of a shark attack while feeding them is lower than diving itself.")

The percentage share of attacks while feeding sharks during the timespan is 8.76%.
Therefore, the chance of a shark attack while feeding them is lower than diving itself.